import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Front site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ul className="list-group">
          <li className="list-group-item list-group-item-success d-grid">
            <a href="cards/frog" className="btn btn-block btn-success">
              <i className="bi bi-backspace-fill"/>
              frog</a>
          </li>
        </ul>
      </main>
    </div>
    
  )
}