import Head from 'next/head'

export default function Home() {
  return (
    <div className="main-body">
      <Head>
        <title>Front site</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <nav>
          <div class="title-bar">
            {/* <div class="title-bar-text">A Title Bar</div>
            <div class="title-bar-controls">
              <button aria-label="Minimize"></button>
              <button aria-label="Maximize"></button>
              <button aria-label="Close"></button> */}
          </div>
        </div>

        </nav>
      </main>
    </div>
    
  )
}